### ISSUE TITLE
Update bleve implmentation

### ISSUE THREAD

**Issue by SpencerDawson** [ecksbee/kushim#8]

**Comment by joshuanario** [comment]
- bleve’s index name (there should be a folders for each taxonomy code dedicated to each bleve index instead of “concepts.bleve”; eg: “indexed/usgaap2024.bleve/“, indexed/usgaap2020.bleve/“, “indexed/sec.bleve/“)
- search api endpoints should: http://localhost:8080/concepts/search?indexName=usgaap2024
